import './style.css';
import {COLORS,LABELS,SYMBOLS,FINISH,syncPiece} from './board.js';
import {DEFAULT_SETTINGS,createGame,currentPlayer,dispatch,getValidMoves,rollDice} from './engine.js';
import {chooseMove} from './ai.js';
import {read,write,loadGame,saveGame,clearGame,recordGame,emptyStats} from './storage.js';
import {AudioManager} from './audio.js';
import {BoardView} from './board-view.js';
const app=document.querySelector('#app');
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let settings={...DEFAULT_SETTINGS,...read('settings',{})};if(!read('settings')&&matchMedia('(prefers-reduced-motion: reduce)').matches)settings.reduceMotion=true;
let game=null,board=null,screen='menu',paused=false,busy=false,epoch=0,pending=null,deadline=0,lastTick=Date.now(),timerRemaining=null,debugDice=null;
const audio=new AudioManager(settings);
const delay=ms=>new Promise(resolve=>setTimeout(resolve,settings.reduceMotion?Math.min(ms,90):ms/settings.animationSpeed));
const minutes=ms=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
function applyVisual(){document.documentElement.classList.toggle('reduced-motion',settings.reduceMotion);document.documentElement.style.setProperty('--move-time',`${settings.reduceMotion?0:135/settings.animationSpeed}ms`);}
applyVisual();
function cancel(){epoch++;clearTimeout(pending);pending=null;deadline=0;busy=false;}
function toast(message){let node=document.querySelector('.toast');if(!node){node=document.createElement('div');node.className='toast';node.setAttribute('role','status');document.body.append(node);}node.textContent=message;clearTimeout(node.timer);node.timer=setTimeout(()=>node.remove(),3400);}
function persist(){if(game&&!saveGame(game))toast('Penyimpanan tidak tersedia. Permainan tetap bisa dimainkan.');}
function shell(content){app.innerHTML=`<header class="topbar"><button class="brand" data-action="home"><span class="brand-icon">⚄</span><span>LUDO<span class="brand-light">CLUB</span><small>A LITTLE LUCK. A LOT OF FUN.</small></span></button><div class="top-actions"><span class="offline"><i></i> Offline & siap dimainkan</span><button class="icon-button" data-action="sound" aria-label="Aktifkan atau matikan suara">${settings.mute?'♩':'♫'}</button><button class="icon-button" data-action="settings" aria-label="Pengaturan">⚙</button></div></header>${content}<footer>Dibuat untuk momen bersama <span>◆ &nbsp; ♣ &nbsp; ☀ &nbsp; ●</span> 2–4 pemain · Tanpa akun</footer>`;}
function menu(){cancel();audio.stop();screen='menu';paused=false;game=null;const saved=loadGame();shell(`<main class="menu-layout"><section class="hero"><div class="eyebrow"><span></span> THE CLASSIC, REIMAGINED</div><h1>Giliranmu.<br>Keseruan <em>kita.</em></h1><p>Empat warna, satu tujuan. Kumpulkan teman atau tantang bot — perjalanan menuju kemenangan dimulai dari satu lemparan.</p><div class="hero-actions"><button class="primary large" data-action="setup">Ayo main <span>↗</span></button>${saved&&saved.turnState!=='GAME_OVER'?'<button class="secondary large" data-action="continue">Lanjutkan game ↻</button>':''}</div><div class="hero-notes"><span>✦ Gratis & offline</span><span>◉ Simpan otomatis</span><span>⌘ Main di perangkat apa pun</span></div><div class="mode-cards"><button class="mode-card" data-action="local"><span class="mode-icon lavender">♧</span><strong>Main bersama</strong><small>2–4 pemain · Satu perangkat</small><b>↗</b></button><button class="mode-card" data-action="bot"><span class="mode-icon peach">▣</span><strong>Tantang bot</strong><small>3 tingkat kesulitan</small><b>↗</b></button></div></section><section class="board-showcase"><div class="floating-tag top">✦ Sedikit strategi, banyak cerita.</div><div id="preview-board"></div><div class="floating-tag bottom"><span class="mini-dice">⚅</span> Angka enam? Jalan terus!</div></section><nav class="menu-links"><button data-action="help">ⓘ Cara bermain <span>↗</span></button><button data-action="stats">▥ Statistik & pencapaian <span>↗</span></button><button data-action="credits">♡ Tentang Ludo Club <span>↗</span></button></nav></main>`);
 const preview=new BoardView(document.querySelector('#preview-board'),()=>{},settings);const sample=createGame(COLORS.map(color=>({name:LABELS[color],color,type:'human'})),settings);sample.players.forEach((p,i)=>{p.pieces[0].progress=7+i*3;syncPiece(p.pieces[0],settings);p.pieces[1].progress=i===0?53:15+i;syncPiece(p.pieces[1],settings);});preview.render(sample);
}
function setup(mode='bot'){
 cancel();screen='setup';shell(`<main class="setup-page"><button class="text-button" data-action="home">← Kembali</button><div class="eyebrow">LET’S PLAY</div><h1>Siapkan mejamu.</h1><p class="muted">Pilih teman, warna, dan tantanganmu.</p><form id="setup-form"><div class="setup-controls"><label>Mode permainan<select id="mode"><option value="bot" ${mode==='bot'?'selected':''}>VS Bot</option><option value="local" ${mode==='local'?'selected':''}>Local Multiplayer</option></select></label><label>Jumlah pemain<select id="count"><option value="2">2 pemain</option><option value="3">3 pemain</option><option value="4">4 pemain</option></select></label></div><div id="player-config" class="player-config"></div><div class="setup-bottom"><p>✦ Aturan dan timer dapat diatur melalui ⚙ Pengaturan.</p><button class="primary large" type="submit">Mulai permainan <span>→</span></button></div></form></main>`);
 const render=()=>{const count=Number(document.querySelector('#count').value),type=document.querySelector('#mode').value;document.querySelector('#player-config').innerHTML=Array.from({length:count},(_,i)=>{const color=COLORS[count===2&&i===1?2:i];return `<fieldset class="player-form ${color}"><legend>PEMAIN 0${i+1}</legend><label>Nama<input name="name${i}" maxlength="24" required value="${i===0?'Kamu':type==='bot'?`Bot ${i}`:`Pemain ${i+1}`}"></label><div class="form-pair"><label>Tipe<select name="type${i}"><option value="human">Manusia</option><option value="bot" ${i>0&&type==='bot'?'selected':''}>Bot</option></select></label><label>Warna<select name="color${i}">${COLORS.map(c=>`<option value="${c}" ${color===c?'selected':''}>${SYMBOLS[c]} ${LABELS[c]}</option>`).join('')}</select></label></div><div class="form-pair"><label>Avatar<select name="avatar${i}">${['🙂','😎','🦊','🐱','🤖','🐼'].map((a,j)=>`<option ${j===(i===0?0:i===1?4:i)?'selected':''}>${a}</option>`).join('')}</select></label><label>Kesulitan bot<select name="difficulty${i}"><option value="easy">Easy</option><option value="medium" selected>Medium</option><option value="hard">Hard</option></select></label></div></fieldset>`;}).join('');};render();document.querySelector('#mode').onchange=render;document.querySelector('#count').onchange=render;
 document.querySelector('#setup-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.target),count=Number(document.querySelector('#count').value);const players=Array.from({length:count},(_,i)=>({name:String(data.get(`name${i}`)).trim()||`Pemain ${i+1}`,type:data.get(`type${i}`),color:data.get(`color${i}`),avatar:data.get(`avatar${i}`),botDifficulty:data.get(`difficulty${i}`)}));if(new Set(players.map(p=>p.color)).size!==count)return toast('Setiap pemain harus memilih warna yang berbeda.');start(createGame(players,settings));};
}
function start(state){cancel();game=state;settings={...settings,...state.settings};audio.settings=settings;applyVisual();paused=false;screen='game';shell(`<main class="game-layout"><div class="game-heading"><div><div class="eyebrow">${game.players.some(p=>p.type==='bot')?'SOLO & BOT':'LOCAL MULTIPLAYER'}</div><h1>Let’s roll.</h1></div><button class="secondary" data-action="pause">Ⅱ <span>Jeda</span></button></div><section class="board-container"><div id="game-board"></div><div class="board-caption"><span>✦ Petak bintang = zona aman</span><span id="turn-count"></span></div></section><aside class="game-sidebar"><div id="players" class="player-panels"></div><section class="turn-card"><div class="eyebrow">GILIRAN SEKARANG</div><h2 id="turn-name"></h2><p id="turn-message" aria-live="polite"></p><div class="dice-area"><button id="dice" class="dice" aria-label="Lempar dadu">⚀</button><div><strong id="dice-caption">Siap bermain?</strong><small id="timer"></small></div></div><button id="roll-button" class="primary">Lempar dadu <span>↗</span></button><div id="move-options" class="move-options"></div></section><div class="game-tips"><span>✧</span><p><strong>Satu langkah lebih dekat.</strong><br>Gunakan angka 6 untuk membuka bidak. Lindungi bidakmu di petak bintang.</p></div><button class="text-button" data-action="help">ⓘ Lihat cara bermain</button>${import.meta.env.DEV?'<details class="debug"><summary>Developer tools</summary><div id="debug-controls"></div></details>':''}</aside></main>`);
 board=new BoardView(document.querySelector('#game-board'),id=>move(id),settings);document.querySelector('#dice').onclick=()=>roll();document.querySelector('#roll-button').onclick=()=>roll();if(import.meta.env.DEV)debugPanel();audio.start();lastTick=Date.now();persist();update();if(game.turnState==='GAME_OVER')showResult();else schedule();
}
function update(displayPositions={},diceOverride){if(screen!=='game'||!game)return;const player=currentPlayer(game),select=game.turnState==='SELECTING_PIECE'&&!busy&&!paused;const moves=select&&player.type==='human'?getValidMoves(game):[];board.render(game,moves.map(p=>p.id),displayPositions);
 document.querySelector('#players').innerHTML=game.players.map((p,i)=>`<div class="player-panel ${p.color} ${i===game.currentPlayerIndex?'active':''}"><span class="avatar">${escapeHTML(p.avatar||SYMBOLS[p.color])}</span><div><strong>${escapeHTML(p.name)}</strong><small>${SYMBOLS[p.color]} ${LABELS[p.color]} · ${p.type==='bot'?`Bot ${p.botDifficulty}`:'Pemain lokal'}</small></div><span class="piece-count">${p.rank?`#${p.rank}`:`${p.pieces.filter(x=>x.progress===FINISH).length}<small>/4</small>`}</span></div>`).join('');
 document.querySelector('#turn-name').textContent=`${SYMBOLS[player.color]} ${player.name}`;document.querySelector('.turn-card').dataset.color=player.color;document.querySelector('#turn-message').textContent=paused?'Permainan dijeda':busy?'Sedang berjalan…':game.turnState==='GAME_OVER'?'Permainan selesai':player.type==='bot'?'Bot sedang berpikir…':select?'Pilih bidak yang bercahaya.':'Lempar dadu untuk memulai langkahmu.';
 const value=diceOverride??game.diceValue;document.querySelector('#dice').textContent=value?'⚀⚁⚂⚃⚄⚅'[value-1]:'⚄';document.querySelector('#dice-caption').textContent=value?`Dapat angka ${value}`:'Giliranmu!';const disabled=busy||paused||player.type==='bot'||game.turnState!=='WAITING_FOR_ROLL';document.querySelector('#dice').disabled=disabled;document.querySelector('#roll-button').disabled=disabled;
 document.querySelector('#move-options').innerHTML=moves.map(p=>`<button class="secondary" data-piece="${p.id}">Bidak ${Number(p.id.split('-')[1])+1}</button>`).join('');document.querySelector('#turn-count').textContent=`Giliran ${game.turns} · ${minutes(game.elapsedMs)}`;
}
function schedule(){clearTimeout(pending);deadline=0;if(!game||paused||busy||game.turnState==='GAME_OVER'||screen!=='game')return;const player=currentPlayer(game),token=epoch;const moves=game.turnState==='SELECTING_PIECE'?getValidMoves(game):[];let task=null,wait=0;
 if(player.type==='bot'){wait=game.turnState==='WAITING_FOR_ROLL'?500+Math.random()*650:500;task=()=>game.turnState==='WAITING_FOR_ROLL'?roll(true):move(chooseMove(game,player.botDifficulty).id,true);}
 else if(moves.length===1&&settings.autoMove){wait=450;task=()=>move(moves[0].id,true);}
 if(task){pending=setTimeout(()=>{if(token===epoch&&!paused)task();},settings.reduceMotion?150:wait);}
 if(player.type==='human'&&settings.turnTimer)deadline=Date.now()+settings.turnTimer*1000;
}
async function roll(automatic=false){if(!game||busy||paused||game.turnState!=='WAITING_FOR_ROLL'||(!automatic&&currentPlayer(game).type==='bot'))return;
 clearTimeout(pending);deadline=0;busy=true;const token=epoch;update();const dice=document.querySelector('#dice');dice.classList.add('rolling');audio.play('dice');const value=import.meta.env.DEV&&debugDice?debugDice:rollDice();debugDice=null;
 for(let i=0;i<8;i++){dice.textContent='⚀⚁⚂⚃⚄⚅'[Math.floor(Math.random()*6)];await delay(65);if(token!==epoch)return;}
 dice.classList.remove('rolling');dispatch(game,{type:'ROLL_DICE',value});persist();update({},value);for(const event of game.events){if(event.type==='NO_MOVES')toast('Tidak ada langkah yang valid. Giliran diteruskan.');if(event.type==='TRIPLE_SIX')toast('Tiga angka 6 berturut-turut. Giliran berakhir.');}
 await delay(500);if(token!==epoch)return;busy=false;update({},value);schedule();
}
async function move(id,automatic=false){if(!game||busy||paused||game.turnState!=='SELECTING_PIECE'||(!automatic&&currentPlayer(game).type==='bot'))return;const piece=currentPlayer(game).pieces.find(p=>p.id===id);if(!piece||!getValidMoves(game).includes(piece))return toast('Bidak ini belum bisa digerakkan.');
 clearTimeout(pending);deadline=0;busy=true;const token=epoch;const snapshot=Object.fromEntries(game.players.flatMap(p=>p.pieces).map(p=>[p.id,p.progress]));const from=piece.progress,dice=game.diceValue;
 // Commit and save before animation. Reload always resumes at a complete command boundary.
 dispatch(game,{type:'MOVE_PIECE',pieceId:id});const events=[...game.events];persist();update(snapshot,dice);
 for(let progress=from<0?0:from+1;progress<=piece.progress;progress++){snapshot[id]=progress;update(snapshot,dice);audio.play('move');await delay(145);if(token!==epoch)return;}
 const captures=events.find(e=>e.type==='CAPTURE_PIECE');if(captures){board.flash(captures.pieces);audio.play('capture');toast(`${captures.pieces.length} bidak tertangkap!`);await delay(450);if(token!==epoch)return;}
 if(events.some(e=>e.type==='PIECE_FINISHED')){audio.play('finish');confetti(20);toast('Satu bidak sampai di finish!');}
 for(const event of events.filter(e=>e.type==='PLAYER_FINISHED')){const winner=game.players.find(p=>p.id===event.playerId);toast(`${winner.name} meraih peringkat ${winner.rank}!`);audio.play('victory');confetti(45);}
 busy=false;update({},dice);if(game.turnState==='GAME_OVER'){recordGame(game);showResult();}else schedule();
}
function pauseGame(){if(screen!=='game')return;timerRemaining=deadline?Math.max(0,deadline-Date.now()):null;cancel();paused=true;audio.stop();persist();update();document.querySelector('#dice')?.classList.remove('rolling');}
function resume(){if(screen!=='game')return;paused=false;lastTick=Date.now();audio.start();update();if(game.turnState==='GAME_OVER')showResult();else{schedule();if(timerRemaining!==null&&deadline)deadline=Date.now()+timerRemaining;timerRemaining=null;}}
function modal(title,html,onClose=()=>{}){document.querySelector('dialog')?.remove();const dialog=document.createElement('dialog');dialog.className='modal';dialog.innerHTML=`<div class="modal-heading"><h2>${title}</h2><button class="icon-button" aria-label="Tutup">×</button></div>${html}`;document.body.append(dialog);dialog.querySelector('.modal-heading button').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{dialog.remove();onClose();});dialog.showModal();return dialog;}
function pauseMenu(){pauseGame();const dialog=modal('Istirahat sebentar.',`<p class="muted">Progresmu sudah disimpan secara otomatis.</p><div class="vertical-actions"><button class="primary" data-pause="resume">Lanjut bermain →</button><button class="secondary" data-pause="restart">Mulai ulang</button><button class="secondary" data-pause="settings">Pengaturan</button><button class="text-button" data-pause="menu">Kembali ke menu utama</button></div>`,()=>{if(paused)resume();});dialog.addEventListener('click',e=>{const action=e.target.closest('[data-pause]')?.dataset.pause;if(!action)return;if(action==='resume')dialog.close();if(action==='settings'){dialog.remove();showSettings(true);}if(action==='menu'||action==='restart'){dialog.remove();confirmExit(action);}});}
function confirmExit(action){const dialog=modal(action==='restart'?'Mulai dari awal?':'Kembali ke menu?',`<p class="muted">${action==='restart'?'Progres permainan ini akan diganti dengan permainan baru.':'Permainan disimpan. Kamu bisa melanjutkannya dari menu utama.'}</p><div class="dialog-actions"><button class="secondary" data-confirm="no">Batal</button><button class="primary" data-confirm="yes">${action==='restart'?'Mulai ulang':'Ke menu'}</button></div>`,()=>resume());dialog.querySelector('[data-confirm="no"]').onclick=()=>dialog.close();dialog.querySelector('[data-confirm="yes"]').onclick=()=>{dialog.remove();if(action==='restart')start(createGame(game.players.map(({name,color,type,avatar,botDifficulty})=>({name,color,type,avatar,botDifficulty})),settings));else menu();};}
function showSettings(alreadyPaused=false){const inGame=screen==='game';if(inGame&&!alreadyPaused)pauseGame();const checks=[['autoMove','Otomatis bila hanya satu langkah'],['tripleSix','Akhiri giliran setelah tiga angka 6'],['bonusTurnOnCapture','Bonus giliran setelah capture'],['enableBlockRule','Dua bidak membentuk block'],['safeStarts','Starting tile adalah zona aman'],['reduceMotion','Kurangi animasi'],['haptic','Getaran jika didukung'],['mute','Matikan semua suara']];const dialog=modal('Atur cara bermainmu.',`<form id="settings-form"><div class="settings-section"><h3>Audio</h3><label>Volume musik<input type="range" name="musicVolume" min="0" max="100" value="${settings.musicVolume}"></label><label>Volume efek suara<input type="range" name="sfxVolume" min="0" max="100" value="${settings.sfxVolume}"></label></div><div class="settings-section"><h3>Gameplay & tampilan</h3>${checks.map(([key,label])=>`<label class="check-row">${label}<input type="checkbox" name="${key}" ${settings[key]?'checked':''}></label>`).join('')}<div class="form-pair"><label>Timer tindakan<select name="turnTimer">${[0,10,15,30].map(n=>`<option value="${n}" ${settings.turnTimer===n?'selected':''}>${n?n+' detik':'Off'}</option>`).join('')}</select></label><label>Kecepatan animasi<select name="animationSpeed">${[.7,1,1.5,2].map(n=>`<option value="${n}" ${settings.animationSpeed===n?'selected':''}>${n}×</option>`).join('')}</select></label></div></div><button class="primary full" type="submit">Simpan pengaturan</button></form>`,()=>{if(inGame)resume();});
 dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);checks.forEach(([key])=>settings[key]=data.has(key));for(const key of ['musicVolume','sfxVolume','turnTimer','animationSpeed'])settings[key]=Number(data.get(key));write('settings',settings);audio.settings=settings;applyVisual();timerRemaining=null;if(game){game.settings={...settings};game.players.forEach(p=>p.pieces.forEach(x=>syncPiece(x,settings)));document.querySelectorAll('.tile[data-index]').forEach(tile=>{const index=Number(tile.dataset.index);tile.textContent=([8,21,34,47].includes(index)||(settings.safeStarts&&[0,13,26,39].includes(index)))?'✦':tile.classList.contains('start')?'↗':'';});if(game.turnState==='SELECTING_PIECE'&&!getValidMoves(game).length){toast('Aturan baru berlaku pada giliran berikutnya.');game.settings.enableBlockRule=false;}persist();}dialog.close();};
}
function help(){const inGame=screen==='game';if(inGame)pauseGame();modal('Cara bermain',`<div class="help-list">${[['01','Lempar & buka','Tekan dadu atau tombol Lempar dadu. Angka 6 mengeluarkan satu bidak dari base ke petak awal.'],['02','Pilih langkahmu','Pilih salah satu bidak bercahaya. Setiap lemparan hanya memindahkan satu bidak. Angka 6 memberi giliran tambahan, bahkan jika tidak ada langkah valid.'],['03','Tangkap & berlindung','Mendarat tepat pada lawan mengembalikannya ke base, kecuali di petak bintang. Jika block aktif, dua bidak sewarna menghalangi lawan lewat atau mendarat, termasuk pada zona aman.'],['04','Pulang dengan tepat','Ikuti jalur searah jarum jam lalu masuk jalur berwarna milikmu. Dadu harus tepat untuk finish. Tidak boleh melebihi sisa langkah.'],['05','Raih peringkat','Selesaikan empat bidak untuk meraih peringkat pertama. Pemain lain melanjutkan sampai hanya satu pemain tersisa.'],['06','Aturan pilihan','Pengaturan menyediakan triple-six (lemparan ketiga batal, langkah sebelumnya tetap), bonus capture, safe start, block, auto-move, dan timer per tindakan. Timer memilih langkah otomatis jika waktu habis.']].map(([n,title,text])=>`<div><span>${n}</span><section><h3>${title}</h3><p>${text}</p></section></div>`).join('')}</div>`,()=>{if(inGame)resume();});}
function statistics(){const s=read('stats',emptyStats());const achievements=[['First Victory',s.wins>=1,'Menang 1 game'],['Hunter',s.captures>=10,'Tangkap 10 bidak'],['Destroyer',s.captures>=100,'Tangkap 100 bidak'],['Lucky Six',s.sixes>=20,'Dapat angka 6 sebanyak 20 kali'],['Perfect Game',s.perfect>=1,'Menang tanpa tertangkap'],['Champion',s.wins>=10,'Menang 10 game']];modal('Statistik & pencapaian',`<p class="muted">Statistik pemain manusia dari permainan yang selesai di perangkat ini. Kemenangan lokal berarti ada pemain manusia yang menjadi juara.</p><div class="stat-grid">${[['Game',s.games],['Kemenangan',s.wins],['Win rate',`${s.games?Math.round(s.wins/s.games*100):0}%`],['Capture',s.captures],['Lemparan',s.rolls],['Angka enam',s.sixes],['Bidak finish',s.finished],['Menang tercepat',s.fastest===null?'—':minutes(s.fastest)]].map(([label,value])=>`<div><strong>${value}</strong><small>${label}</small></div>`).join('')}</div><h3>Per mode</h3><p class="muted">VS Bot: ${s.modes.bot?.games||0} game / ${s.modes.bot?.wins||0} menang<br>Local: ${s.modes.local?.games||0} game / ${s.modes.local?.wins||0} menang</p><div class="achievements">${achievements.map(([name,done,description])=>`<div class="${done?'unlocked':''}"><span>${done?'★':'☆'}</span><strong>${name}</strong><small>${description}</small></div>`).join('')}</div>`);}
function confetti(count=45){if(settings.reduceMotion)return;const layer=document.createElement('div');layer.className='confetti';layer.setAttribute('aria-hidden','true');for(let i=0;i<count;i++){const dot=document.createElement('i');dot.style.cssText=`left:${Math.random()*100}%;background:var(--${COLORS[i%4]});animation-delay:${Math.random()*.5}s;transform:rotate(${Math.random()*360}deg)`;layer.append(dot);}document.body.append(layer);setTimeout(()=>layer.remove(),2400);}
function showResult(){audio.stop();recordGame(game);clearGame();const winner=game.players.find(p=>p.id===game.rankings[0]);confetti(70);const dialog=modal('Kemenangan yang manis! ✦',`<div class="winner-avatar">${escapeHTML(winner.avatar||'🏆')}</div><h2 class="center">${escapeHTML(winner.name)} jadi juara!</h2><div class="rank-list">${game.rankings.map((id,i)=>{const player=game.players.find(p=>p.id===id);return `<div><strong>#${i+1}</strong><span>${SYMBOLS[player.color]} ${escapeHTML(player.name)}</span><small>${player.pieces.filter(p=>p.progress===56).length}/4 finish</small></div>`;}).join('')}</div><div class="stat-grid"><div><strong>${minutes(game.elapsedMs)}</strong><small>Durasi aktif</small></div><div><strong>${game.stats.captures}</strong><small>Capture</small></div><div><strong>${game.stats.sixes}</strong><small>Angka enam</small></div><div><strong>${game.stats.rolls}</strong><small>Lemparan</small></div></div><div class="dialog-actions"><button class="secondary" data-result="menu">Menu utama</button><button class="primary" data-result="again">Main lagi ↗</button></div>`);dialog.querySelector('[data-result="menu"]').onclick=()=>{dialog.remove();menu();};dialog.querySelector('[data-result="again"]').onclick=()=>{dialog.remove();start(createGame(game.players.map(({name,color,type,avatar,botDifficulty})=>({name,color,type,avatar,botDifficulty})),settings));};}
function debugPanel(){if(!import.meta.env.DEV)return;const host=document.querySelector('#debug-controls');host.innerHTML=`<label>Dadu berikutnya<select id="debug-dice"><option value="0">Acak</option>${[1,2,3,4,5,6].map(n=>`<option>${n}</option>`).join('')}</select></label><label>Bidak<select id="debug-piece">${game.players.flatMap(p=>p.pieces).map(p=>`<option value="${p.id}">${p.id}</option>`).join('')}</select></label><label>Progress (-1 sampai 56)<input id="debug-progress" type="number" min="-1" max="56" value="50"></label><button data-debug="teleport">Teleport</button><button data-debug="next">Ganti giliran</button><button data-debug="reset">Reset pemain aktif</button><button data-debug="finish">Simulasi finish</button><label><input type="checkbox" id="debug-indices"> Tampilkan indeks tile & progress</label><pre id="debug-state"></pre>`;host.querySelector('#debug-dice').onchange=e=>debugDice=Number(e.target.value)||null;host.querySelector('#debug-indices').onchange=e=>{document.querySelector('#game-board').classList.toggle('show-indices',e.target.checked);host.querySelector('#debug-state').textContent=e.target.checked?game.players.flatMap(p=>p.pieces).map(p=>`${p.id}: ${p.progress}`).join('\n'):'';};host.addEventListener('click',e=>{const action=e.target.dataset.debug;if(!action||busy||paused||game.turnState==='GAME_OVER')return;cancel();const player=currentPlayer(game);if(action==='next'){let next=(game.currentPlayerIndex+1)%game.players.length;while(game.players[next].isFinished)next=(next+1)%game.players.length;game.currentPlayerIndex=next;game.turnState='WAITING_FOR_ROLL';game.diceValue=null;game.consecutiveSixes=0;}if(action==='teleport'){const piece=game.players.flatMap(p=>p.pieces).find(p=>p.id===host.querySelector('#debug-piece').value);const progress=Number(host.querySelector('#debug-progress').value);if(Number.isInteger(progress)&&progress>=-1&&progress<=56){piece.progress=progress;syncPiece(piece,settings);}}if(action==='reset')player.pieces.forEach(p=>{p.progress=-1;syncPiece(p,settings);});if(action==='finish'){player.pieces.forEach((p,i)=>{p.progress=i===3?55:56;syncPiece(p,settings);});game.turnState='SELECTING_PIECE';game.diceValue=1;}persist();update();schedule();});}
app.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;try{audio.unlock();audio.play('click');}catch{}if(target.dataset.piece)return move(target.dataset.piece);const action=target.dataset.action;if(action==='home'){if(screen==='game')pauseMenu();else menu();}if(action==='setup'||action==='bot')setup('bot');if(action==='local')setup('local');if(action==='continue'){const saved=loadGame();if(saved)start(saved);else toast('Tidak ada permainan tersimpan yang valid.');}if(action==='pause')pauseMenu();if(action==='settings')showSettings();if(action==='help')help();if(action==='stats')statistics();if(action==='credits')modal('Tentang Ludo Club',`<p>Ludo klasik, dibangun ulang untuk waktu berkualitas bersama. Bisa dimainkan secara lokal, tanpa akun dan tanpa layanan eksternal.</p><p class="muted">Desain, papan, animasi, dan audio sintetis dibuat sebagai bagian dari proyek ini. Tidak memakai aset audio atau gambar berlisensi pihak ketiga.</p><p class="muted">Versi 1.0 · JavaScript modules · Vite</p>`);if(action==='sound'){settings.mute=!settings.mute;audio.settings=settings;write('settings',settings);if(game){game.settings.mute=settings.mute;persist();}target.textContent=settings.mute?'♩':'♫';}});
setInterval(()=>{const now=Date.now(),delta=Math.min(now-lastTick,2000);lastTick=now;if(screen!=='game'||!game||paused||game.turnState==='GAME_OVER')return;game.elapsedMs+=delta;const timer=document.querySelector('#timer');if(timer)timer.textContent=deadline?`${Math.max(0,Math.ceil((deadline-now)/1000))} detik tersisa`:'Tanpa terburu-buru';if(deadline&&now>=deadline&&!busy){deadline=0;if(game.turnState==='WAITING_FOR_ROLL')roll(true);else{const piece=chooseMove(game,'medium');if(piece)move(piece.id,true);}}},250);
setInterval(()=>{if(game&&screen==='game'&&game.turnState!=='GAME_OVER')persist();},5000);
window.addEventListener('pagehide',()=>{if(game&&game.turnState!=='GAME_OVER')persist();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='game'&&!paused&&game.turnState!=='GAME_OVER')pauseMenu();});
menu();
